name: supabase_auth
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^0.2.6
  flutter_svg: ^1.0.0
  get: 4.6.5
  shared_preferences: ^2.0.18
  cached_network_image: ^3.2.3
  syncfusion_flutter_datepicker: ^20.4.53
  flutter_time_picker_spinner: ^2.0.0
  awesome_select: ^6.0.0
  url_launcher: ^6.1.10
  http: ^0.13.5
  injectable: ^2.1.1
  googleapis_auth: ^1.4.0
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^13.1.0
  firebase_core: ^1.24.0
  googleapis: ^3.0.0
  google_sign_in: ^5.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700

  